### ISSUE TITLE
how i can pass this params

### ISSUE THREAD

**Issue by nazaninhesari** [Sempro/vue-url-parameters#5]
i have this structure please help  me how i can set to url  just key ?

example :+1: 
user=1&type=2

 

```
				 params:{
					user:{
						key:null,
						value:null,
					},
					type:{
						key:null,
						value:null,
					},
					created_at:{
						key:null,
						value:null,
					},					
	
				 },
```

**Comment by ventrec** [comment]
I don't think that's possible. If I remember correctly it only supports one level inside of `params`. So if you want it to work you could do something like this:

```js
params: {
  user_key: null,
  user_value: null,
  type_key: null,
  ...
}
```

**Comment by nazaninhesari** [comment]
it tested  it but my structure is this.

**Comment by ventrec** [comment]
You will have to change your structure in order for this package to work. If you can't do that you'll have to either add support for it in this package and submit a PR or find an other solution.

**Comment by nazaninhesari** [comment]
i change line 120 to  this

```let value = data[key].key;```

work correctly  !!!
